### ISSUE TITLE
After Authentication Always redirect to "User Registration Page"

### ISSUE THREAD

**Issue by abassanini** [kevinoconnor7/osTicket-auth-mail#1]
I successfully installed the plugin, and the authentication works fine, but after first authentincation, it redirects the user to the "User Registrarion Page".  The user fills out and submit the form, and the page says "The user is already registered" and give the option to go to login page.  Again in the login page, after authentication, the "User Registrarion Page" apperas again, and the user is in a loop.  

Any help in this, please?

## Installation Info
```
osTicket Version 	v1.9.15 (70898b3)
Web Server Software 	Apache/2.4.7 (Ubuntu)
MySQL Version 	5.6.33
PHP Version 	5.5.9-1ubuntu4.21
PHP Extensions
gdlib 	Used for image manipulation and PDF printing
imap 	Used for email fetching
xml 	XML API
xml-dom 	Used for HTML email processing
json 	Improves performance creating and processing JSON
mbstring 	Highly recommended for non western european language content
phar 	Highly recommended for plugins and language packs
fileinfo 	Used to detect file types for uploads 
```
## After Login Page:

![imagen](https://cloud.githubusercontent.com/assets/11131009/25558262/ae44bb30-2ce8-11e7-86b8-02e199976e17.png)

## After Submit Page:
![imagen](https://cloud.githubusercontent.com/assets/11131009/25558271/d3302cc2-2ce8-11e7-8f27-dfd97617b129.png)

**Comment by kevinoconnor7** [comment]
I believe edc54d2 also fixed this.
